FROM python:3.10-slim

WORKDIR /app

COPY src/system_checker/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/system_checker/ /app/

CMD ["python", "test.py"]