FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc curl && \
    rm -rf /var/lib/apt/lists/*

COPY src/api_user/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app \
    DASH_DEBUG_MODE=True

WORKDIR /app/src/api_user/visualization

CMD ["python", "dash_app.py"]